spring:
  application:
    name: user-service

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop

eureka:
  instance:
    instance_id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka


jwt:
  secret-key: skjfefiajiejiwljifjeuijliuhufhhiuhu129472189eaf_ekiaeoifn23929fjskg94
  token:
    expired-time-ms: 2592000000 # 30 days